import JSZip from 'jszip'

/**
 * Load an image file into an HTMLImageElement
 */
export function loadImageFromFile(file) {
  return new Promise((resolve, reject) => {
    const url = URL.createObjectURL(file)
    const img = new Image()
    img.onload = () => {
      URL.revokeObjectURL(url)
      resolve(img)
    }
    img.onerror = (err) => {
      URL.revokeObjectURL(url)
      reject(err)
    }
    img.src = url
  })
}

/**
 * Compress an image with quality slider and optional max dimension scaling
 */
export async function compressImage(file, { quality = 0.8, maxWidth = 0, maxHeight = 0, mimeType = 'image/jpeg' } = {}) {
  const img = await loadImageFromFile(file)
  let width = img.naturalWidth
  let height = img.naturalHeight

  if (maxWidth > 0 && width > maxWidth) {
    height = Math.round((height * maxWidth) / width)
    width = maxWidth
  }
  if (maxHeight > 0 && height > maxHeight) {
    width = Math.round((width * maxHeight) / height)
    height = maxHeight
  }

  const canvas = document.createElement('canvas')
  canvas.width = width
  canvas.height = height
  const ctx = canvas.getContext('2d')
  ctx.imageSmoothingEnabled = true
  ctx.imageSmoothingQuality = 'high'
  ctx.drawImage(img, 0, 0, width, height)

  const blob = await new Promise(resolve => canvas.toBlob(resolve, mimeType, quality))
  return {
    blob,
    width,
    height,
    originalSize: file.size,
    compressedSize: blob.size,
    savingsPercent: Math.max(0, Math.round(((file.size - blob.size) / file.size) * 100)),
    dataUrl: canvas.toDataURL(mimeType, quality)
  }
}

/**
 * Convert Image Format (PNG, JPG, WebP)
 */
export async function convertImageFormat(file, targetFormat = 'image/webp', quality = 0.92) {
  const img = await loadImageFromFile(file)
  const canvas = document.createElement('canvas')
  canvas.width = img.naturalWidth
  canvas.height = img.naturalHeight
  const ctx = canvas.getContext('2d')

  // If converting to JPEG, draw white background first in case source has transparency
  if (targetFormat === 'image/jpeg') {
    ctx.fillStyle = '#ffffff'
    ctx.fillRect(0, 0, canvas.width, canvas.height)
  }

  ctx.drawImage(img, 0, 0)
  const blob = await new Promise(resolve => canvas.toBlob(resolve, targetFormat, quality))
  return {
    blob,
    width: canvas.width,
    height: canvas.height,
    size: blob.size,
  }
}

/**
 * Generate complete Favicon & App Icon pack (16x16 to 512x512) and bundle into ZIP
 */
export async function generateFaviconPack(file, progressCb = () => {}) {
  const img = await loadImageFromFile(file)
  const zip = new JSZip()
  const sizes = [
    { name: 'favicon-16x16.png', size: 16 },
    { name: 'favicon-32x32.png', size: 32 },
    { name: 'favicon-48x48.png', size: 48 },
    { name: 'apple-touch-icon-180x180.png', size: 180 },
    { name: 'android-chrome-192x192.png', size: 192 },
    { name: 'android-chrome-512x512.png', size: 512 },
  ]

  for (let i = 0; i < sizes.length; i++) {
    const { name, size } = sizes[i]
    progressCb(Math.round(((i + 1) / sizes.length) * 80))
    const canvas = document.createElement('canvas')
    canvas.width = size
    canvas.height = size
    const ctx = canvas.getContext('2d')
    ctx.imageSmoothingEnabled = true
    ctx.imageSmoothingQuality = 'high'
    ctx.drawImage(img, 0, 0, size, size)

    const blob = await new Promise(res => canvas.toBlob(res, 'image/png'))
    const arrayBuf = await blob.arrayBuffer()
    zip.file(name, arrayBuf)
  }

  // Include a ready-to-paste HTML snippet
  const htmlSnippet = `<!-- Favicon and App Icons generated by PDFZero -->
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
<link rel="manifest" href="/site.webmanifest">
`
  zip.file('favicon_html_tags.html', htmlSnippet)

  const webmanifest = JSON.stringify({
    name: "My App",
    short_name: "App",
    icons: [
      { src: "/android-chrome-192x192.png", sizes: "192x192", type: "image/png" },
      { src: "/android-chrome-512x512.png", sizes: "512x512", type: "image/png" }
    ],
    theme_color: "#ffffff",
    background_color: "#ffffff",
    display: "standalone"
  }, null, 2)
  zip.file('site.webmanifest', webmanifest)

  progressCb(95)
  const zipBlob = await zip.generateAsync({ type: 'blob' })
  progressCb(100)
  return zipBlob
}

/**
 * Apply Photo Filters
 */
export async function applyPhotoFilters(file, filters = {}) {
  const {
    brightness = 100,
    contrast = 100,
    saturation = 100,
    blur = 0,
    grayscale = 0,
    sepia = 0,
    invert = 0,
    hueRotate = 0
  } = filters

  const img = await loadImageFromFile(file)
  const canvas = document.createElement('canvas')
  canvas.width = img.naturalWidth
  canvas.height = img.naturalHeight
  const ctx = canvas.getContext('2d')

  const filterString = [
    `brightness(${brightness}%)`,
    `contrast(${contrast}%)`,
    `saturate(${saturation}%)`,
    `blur(${blur}px)`,
    `grayscale(${grayscale}%)`,
    `sepia(${sepia}%)`,
    `invert(${invert}%)`,
    `hue-rotate(${hueRotate}deg)`
  ].join(' ')

  ctx.filter = filterString
  ctx.drawImage(img, 0, 0)

  const blob = await new Promise(res => canvas.toBlob(res, 'image/png'))
  return {
    blob,
    dataUrl: canvas.toDataURL('image/png')
  }
}

/**
 * Generate Classic Impact Meme
 */
export async function generateMeme(file, {
  topText = '',
  bottomText = '',
  fontSize = 42,
  fontFamily = 'Impact, sans-serif',
  textColor = '#ffffff',
  strokeColor = '#000000',
  strokeWidth = 4,
  allCaps = true
} = {}) {
  const img = await loadImageFromFile(file)
  const canvas = document.createElement('canvas')
  canvas.width = img.naturalWidth
  canvas.height = img.naturalHeight
  const ctx = canvas.getContext('2d')

  ctx.drawImage(img, 0, 0)

  const top = allCaps ? topText.toUpperCase() : topText
  const bottom = allCaps ? bottomText.toUpperCase() : bottomText

  ctx.font = `bold ${fontSize}px ${fontFamily}`
  ctx.textAlign = 'center'
  ctx.fillStyle = textColor
  ctx.strokeStyle = strokeColor
  ctx.lineWidth = strokeWidth
  ctx.lineJoin = 'round'

  if (top) {
    const y = fontSize + 20
    ctx.strokeText(top, canvas.width / 2, y)
    ctx.fillText(top, canvas.width / 2, y)
  }

  if (bottom) {
    const y = canvas.height - 25
    ctx.strokeText(bottom, canvas.width / 2, y)
    ctx.fillText(bottom, canvas.width / 2, y)
  }

  const blob = await new Promise(res => canvas.toBlob(res, 'image/png'))
  return {
    blob,
    dataUrl: canvas.toDataURL('image/png')
  }
}

/**
 * Extract dominant color palette using canvas pixel sampling
 */
export async function extractColorPalette(file, maxColors = 6) {
  const img = await loadImageFromFile(file)
  const canvas = document.createElement('canvas')
  // Scale down for ultra-fast sampling
  const scale = Math.min(1, 200 / Math.max(img.naturalWidth, img.naturalHeight))
  canvas.width = Math.max(1, Math.round(img.naturalWidth * scale))
  canvas.height = Math.max(1, Math.round(img.naturalHeight * scale))
  const ctx = canvas.getContext('2d')
  ctx.drawImage(img, 0, 0, canvas.width, canvas.height)

  const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height).data
  const colorBuckets = {}

  // Sample every 4th pixel
  for (let i = 0; i < imageData.length; i += 16) {
    const r = imageData[i]
    const g = imageData[i + 1]
    const b = imageData[i + 2]
    const a = imageData[i + 3]
    if (a < 128) continue // skip transparent

    // Quantize to 32 steps
    const qr = Math.round(r / 32) * 32
    const qg = Math.round(g / 32) * 32
    const qb = Math.round(b / 32) * 32
    const key = `${qr},${qg},${qb}`

    colorBuckets[key] = (colorBuckets[key] || 0) + 1
  }

  const sorted = Object.entries(colorBuckets)
    .sort((a, b) => b[1] - a[1])
    .slice(0, maxColors)

  return sorted.map(([rgbStr]) => {
    const [r, g, b] = rgbStr.split(',').map(Number)
    const hex = '#' + [r, g, b].map(x => x.toString(16).padStart(2, '0')).join('')
    // Calculate luminance to decide text color (white or black)
    const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255
    return {
      hex,
      rgb: `rgb(${r}, ${g}, ${b})`,
      isDark: luminance < 0.5,
    }
  })
}

/**
 * Rasterize SVG to high-resolution PNG
 */
export async function rasterizeSvg(fileOrText, scale = 2) {
  let svgString = ''
  if (typeof fileOrText === 'string') {
    svgString = fileOrText
  } else {
    svgString = await fileOrText.text()
  }

  const parser = new DOMParser()
  const doc = parser.parseFromString(svgString, 'image/svg+xml')
  const svgEl = doc.querySelector('svg')
  if (!svgEl) throw new Error('Invalid SVG content')

  let width = parseFloat(svgEl.getAttribute('width')) || 400
  let height = parseFloat(svgEl.getAttribute('height')) || 400

  if (svgEl.hasAttribute('viewBox')) {
    const vb = svgEl.getAttribute('viewBox').split(/\s+|,/).map(Number)
    if (vb.length === 4 && vb[2] > 0 && vb[3] > 0) {
      width = vb[2]
      height = vb[3]
    }
  }

  const blob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' })
  const url = URL.createObjectURL(blob)

  const img = new Image()
  return new Promise((resolve, reject) => {
    img.onload = () => {
      URL.revokeObjectURL(url)
      const canvas = document.createElement('canvas')
      canvas.width = Math.round(width * scale)
      canvas.height = Math.round(height * scale)
      const ctx = canvas.getContext('2d')
      ctx.drawImage(img, 0, 0, canvas.width, canvas.height)
      canvas.toBlob(pngBlob => {
        resolve({
          blob: pngBlob,
          width: canvas.width,
          height: canvas.height,
          dataUrl: canvas.toDataURL('image/png')
        })
      }, 'image/png')
    }
    img.onerror = (err) => {
      URL.revokeObjectURL(url)
      reject(err)
    }
    img.src = url
  })
}
